seed: 1234
tag: lora_single
log_dir: ./output

model_type: 'mae_vitb16'
feat_type: 'last_layer'
stride: '16'
use_lora: True

dataset_root: ./dataset/nights
num_workers: 4

lr: 0.0003
weight_decay: 0.0
batch_size: 32
epochs: 8
margin: 0.05

lora_r: 16
lora_alpha: 0.5
lora_dropout: 0.3